# Generated by Django 3.2.7 on 2022-01-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_register_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
        migrations.AddField(
            model_name='register',
            name='female',
            field=models.BooleanField(default=False, verbose_name='IS Female'),
        ),
        migrations.AddField(
            model_name='register',
            name='male',
            field=models.BooleanField(default=True, verbose_name='IS male'),
        ),
        migrations.AddField(
            model_name='register',
            name='others',
            field=models.BooleanField(default=False, verbose_name='IS other'),
        ),
    ]
