# Generated by Django 3.2.7 on 2022-01-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220119_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='male',
            field=models.BooleanField(default=True, verbose_name='male'),
        ),
    ]
