# Generated by Django 3.2.7 on 2022-01-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_register_male'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='others',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='register',
            name='female',
        ),
        migrations.RemoveField(
            model_name='register',
            name='male',
        ),
    ]
