# Generated by Django 3.2.7 on 2022-01-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_register_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='gender',
            new_name='other',
        ),
        migrations.AddField(
            model_name='register',
            name='female',
            field=models.BooleanField(default=False, verbose_name='Female'),
        ),
        migrations.AddField(
            model_name='register',
            name='male',
            field=models.BooleanField(default=False, verbose_name='Male'),
        ),
    ]
