# Generated by Django 3.2.7 on 2022-01-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220119_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='other',
        ),
    ]
